ALTER TABLE users
    ADD COLUMN IF NOT EXISTS is_deleted BOOLEAN NOT NULL DEFAULT false;

CREATE INDEX IF NOT EXISTS idx_users_is_deleted
    ON users (is_deleted);

ALTER TABLE users
    ADD COLUMN IF NOT EXISTS password TEXT NOT NULL DEFAULT '123456';
